// Sales rep directory — seeded from the master rep roster (Book1.xlsx).
// Reference data kept in-repo so the Sales Team page works without a DB round-trip.
// To update: edit this list, or re-run the generator against an updated roster.

export type SalesRep = {
  /** DB primary key. Absent on the built-in seed rows (read-only fallback). */
  id?: string;
  /** Rep-agency account code (e.g. 210 = Sales Producers). */
  agencyCode: number;
  agency: string;
  name: string;
  /** Lowercased; empty string when none is on file. */
  email: string;
  phone: string;
  /**
   * Street line. Optional because the built-in roster below predates the field
   * and has never carried one — DB-backed reps always get a string (possibly
   * empty) from `fromRow`.
   */
  address?: string;
  city: string;
  state: string;
  zip: string;
  /** Territory / role note from the roster. */
  territory: string;
  /** Sample + catalog allocation tier (A, B, Cat, Cat+, NA, "2 catalogs"). */
  samples: string;
};

export const SALES_REPS: SalesRep[] = [
  {
    "agencyCode": 101,
    "agency": "Blonde Comet",
    "name": "Tana Erickson",
    "address": "8941 Audubon Rd",
    "email": "blondecomet@gmail.com",
    "phone": "612-281-7921",
    "city": "Chanhassen",
    "state": "MN",
    "zip": "55317",
    "territory": "Principal",
    "samples": "A"
  },
  {
    "agencyCode": 101,
    "agency": "Blonde Comet",
    "name": "Karri Kearin",
    "address": "14829 64th Place N",
    "email": "karri.vanliermann@gmail.com",
    "phone": "763-226-6359",
    "city": "Maple Grove",
    "state": "MN",
    "zip": "55311",
    "territory": "Northern MN",
    "samples": "A"
  },
  {
    "agencyCode": 101,
    "agency": "Blonde Comet",
    "name": "Jill Rowley",
    "address": "912 E 4th Ave",
    "email": "rowleyjill@gmail.com",
    "phone": "605-770-0045",
    "city": "Mitchell",
    "state": "SD",
    "zip": "57301",
    "territory": "South Dakota",
    "samples": "A"
  },
  {
    "agencyCode": 101,
    "agency": "Blonde Comet",
    "name": "Meg Brownson",
    "address": "1512 Linden Street West",
    "email": "megbrownson@msnc.om",
    "phone": "651-324-4502",
    "city": "Stillwater",
    "state": "MN",
    "zip": "55082",
    "territory": "Wisconsin and Eastern MN",
    "samples": "A"
  },
  {
    "agencyCode": 101,
    "agency": "Blonde Comet",
    "name": "Sue Ferlita",
    "address": "3966 Arlene Court",
    "email": "ferlita@comcast.net",
    "phone": "",
    "city": "Eagan",
    "state": "MN",
    "zip": "55123",
    "territory": "LFHI",
    "samples": "A"
  },
  {
    "agencyCode": 101,
    "agency": "Blonde Comet",
    "name": "Angela Schumacher",
    "address": "3520 County Road 101",
    "email": "schumangie@gmail.com",
    "phone": "",
    "city": "Minnetonka",
    "state": "MN",
    "zip": "55345",
    "territory": "LFHI",
    "samples": "A"
  },
  {
    "agencyCode": 101,
    "agency": "Blonde Comet",
    "name": "Jeanne Kenney",
    "address": "139 Dunlap Street North",
    "email": "kenneysalesllc@gmail.com",
    "phone": "",
    "city": "St. Paul",
    "state": "MN",
    "zip": "55104",
    "territory": "LFHI",
    "samples": "A"
  },
  {
    "agencyCode": 101,
    "agency": "Blonde Comet",
    "name": "Jill Hauch",
    "address": "8167 Arrowwood Lane",
    "email": "jhauchllc@gmail.com",
    "phone": "",
    "city": "Maple Grove",
    "state": "MN",
    "zip": "55369",
    "territory": "LFHI",
    "samples": "B"
  },
  {
    "agencyCode": 101,
    "agency": "Blonde Comet",
    "name": "Judy Schierman",
    "address": "4735 Kent Street",
    "email": "jschierman@gmail.com",
    "phone": "",
    "city": "Shoreview",
    "state": "MN",
    "zip": "55126",
    "territory": "LFHI",
    "samples": "A"
  },
  {
    "agencyCode": 101,
    "agency": "Blonde Comet",
    "name": "Molly Swenson",
    "address": "8581 Mission Hills Lane",
    "email": "msmarketing2021@gmail.com",
    "phone": "",
    "city": "Chanhassen",
    "state": "MN",
    "zip": "55317",
    "territory": "LFHI",
    "samples": "B"
  },
  {
    "agencyCode": 101,
    "agency": "Blonde Comet",
    "name": "Karen VanMeter",
    "address": "12445 Destin Loop",
    "email": "klvanmeter@gmail.com",
    "phone": "",
    "city": "Venice",
    "state": "FL",
    "zip": "34293",
    "territory": "LFHI",
    "samples": "B"
  },
  {
    "agencyCode": 101,
    "agency": "Blonde Comet",
    "name": "Jennifer Calhoun",
    "address": "405 South Olde Oneida",
    "email": "olive.opal0@gmail.com",
    "phone": "715.612.2949",
    "city": "Menasha",
    "state": "WI",
    "zip": "54952",
    "territory": "WI",
    "samples": "A"
  },
  {
    "agencyCode": 111,
    "agency": "Hofstedt",
    "name": "Julie Hofstedt",
    "address": "674 Minnow Lane NE",
    "email": "julieh@fragrancemarketinggroup.com",
    "phone": "612.201.3140",
    "city": "Longville",
    "state": "MN",
    "zip": "56655",
    "territory": "Inside Sales Key Account",
    "samples": "Cat"
  },
  {
    "agencyCode": 178,
    "agency": "GMA",
    "name": "Gretchen Mathey",
    "address": "7426 Cottonwood Drive",
    "email": "gmatheny4@gmail.com",
    "phone": "419.367.9035",
    "city": "Plain City",
    "state": "OH",
    "zip": "43064",
    "territory": "Columbus OH",
    "samples": "A"
  },
  {
    "agencyCode": 178,
    "agency": "GMA",
    "name": "Jenni Dahlinghaus",
    "address": "224 S. Garfield Street",
    "email": "jdahlinghaus@yahoo.com",
    "phone": "419.305.8061",
    "city": "Minster",
    "state": "OH",
    "zip": "45865",
    "territory": "Dayton OH",
    "samples": "A"
  },
  {
    "agencyCode": 178,
    "agency": "GMA",
    "name": "Corey Fowles",
    "address": "10986 Fawn Madow Lane",
    "email": "ctfowles@gmail.com",
    "phone": "440.665.4768",
    "city": "Strongsville",
    "state": "OH",
    "zip": "44149",
    "territory": "Toledo, OH",
    "samples": "A"
  },
  {
    "agencyCode": 178,
    "agency": "GMA",
    "name": "Ted Fowles",
    "address": "10986 Fawn Madow Lane",
    "email": "ctfowles@gmail.com",
    "phone": "440.665.4781",
    "city": "Strongsville",
    "state": "OH",
    "zip": "44149",
    "territory": "OH",
    "samples": "A"
  },
  {
    "agencyCode": 178,
    "agency": "GMA",
    "name": "Stephanie Lark",
    "address": "2690 Northmont Drive",
    "email": "stephanielark@hotmail.com",
    "phone": "",
    "city": "Blacklick",
    "state": "OH",
    "zip": "43004",
    "territory": "OH",
    "samples": "A"
  },
  {
    "agencyCode": 183,
    "agency": "Jim Dedricks Assoc",
    "name": "Jim Dedricks",
    "address": "4624 North Haymeadow Avenue",
    "email": "jrdedricks@gmail.com",
    "phone": "920-285-3636",
    "city": "Appleton",
    "state": "WI",
    "zip": "54913",
    "territory": "Michigan",
    "samples": "A"
  },
  {
    "agencyCode": 183,
    "agency": "Jim Dedricks Assoc",
    "name": "Bryce Alvarado",
    "address": "864 Hunt Avenue",
    "email": "brycealvarado15@gmail.com",
    "phone": "920-252-2289",
    "city": "Neenah",
    "state": "WI",
    "zip": "54956",
    "territory": "Michigan",
    "samples": "A"
  },
  {
    "agencyCode": 183,
    "agency": "Jim Dedricks Assoc",
    "name": "Josh Broek",
    "address": "6340 Thornhill Court",
    "email": "cbbroek@comcast.net",
    "phone": "",
    "city": "Hudsonville",
    "state": "WI",
    "zip": "49426",
    "territory": "Michigan",
    "samples": "B"
  },
  {
    "agencyCode": 190,
    "agency": "Keith Smith",
    "name": "KERRY SMITH",
    "address": "Dallas World Trade Center",
    "email": "kerry@keithsmithltd.com",
    "phone": "214.809.8774",
    "city": "Dallas",
    "state": "TX",
    "zip": "75207",
    "territory": "Principal",
    "samples": "NA"
  },
  {
    "agencyCode": 190,
    "agency": "Keith Smith",
    "name": "JANET SMITH",
    "address": "2050 N. Stemmons Fwy Suite 200",
    "email": "janet@keithsmithltd.com",
    "phone": "972.977.3879",
    "city": "Dallas",
    "state": "TX",
    "zip": "75207",
    "territory": "Principal",
    "samples": "NA"
  },
  {
    "agencyCode": 190,
    "agency": "Keith Smith",
    "name": "KELLY BURNS",
    "address": "2050 N. Stemmons Fwy Suite 200",
    "email": "kelly@keithsmithltd.com",
    "phone": "214.741.4392",
    "city": "Dallas",
    "state": "TX",
    "zip": "75207",
    "territory": "Admin/Showroom",
    "samples": "NA"
  },
  {
    "agencyCode": 190,
    "agency": "Keith Smith",
    "name": "Tanya Day",
    "address": "689 Redoak Drive",
    "email": "tanya@keithsmithltd.com",
    "phone": "870.377.1246",
    "city": "Hot Springs",
    "state": "AR",
    "zip": "71913",
    "territory": "Arkansas",
    "samples": "A"
  },
  {
    "agencyCode": 190,
    "agency": "Keith Smith",
    "name": "Deborah Vinson",
    "address": "3446 Magazine Street",
    "email": "deborah@keithsmithltd.com",
    "phone": "312.315.1565",
    "city": "New Orleans",
    "state": "LA",
    "zip": "70115",
    "territory": "Louisiana",
    "samples": "B"
  },
  {
    "agencyCode": 190,
    "agency": "Keith Smith",
    "name": "Lora Frazier",
    "address": "706 Main Street",
    "email": "",
    "phone": "",
    "city": "Stillwater",
    "state": "OK",
    "zip": "74074",
    "territory": "",
    "samples": "B"
  },
  {
    "agencyCode": 190,
    "agency": "Keith Smith",
    "name": "Cipres Guillermo",
    "address": "11419 Chaucer Drive",
    "email": "guillermo@keithsmithltd.com",
    "phone": "214-994-4827",
    "city": "Frisco",
    "state": "TX",
    "zip": "75035",
    "territory": "Mexico",
    "samples": "B"
  },
  {
    "agencyCode": 190,
    "agency": "Keith Smith",
    "name": "Dina Shaw",
    "address": "1343 Doss Loop",
    "email": "dinashaw02@gmail.com",
    "phone": "214.708.5064",
    "city": "Ringgold",
    "state": "TX",
    "zip": "76261",
    "territory": "West Texas",
    "samples": ""
  },
  {
    "agencyCode": 190,
    "agency": "Keith Smith",
    "name": "Marsha Waugh",
    "address": "3733 Ashford Ave",
    "email": "marsha@keithsmithltd.com",
    "phone": "817.999.0881",
    "city": "Fort Worth",
    "state": "TX",
    "zip": "76133",
    "territory": "Fort Worth",
    "samples": "A"
  },
  {
    "agencyCode": 190,
    "agency": "Keith Smith",
    "name": "Mary Lazauskas",
    "address": "11 Box Turtle Lane",
    "email": "marylaz@keithsmithltd.com",
    "phone": "281.650.1227",
    "city": "The Woodlands",
    "state": "TX",
    "zip": "77380",
    "territory": "Houston",
    "samples": "A"
  },
  {
    "agencyCode": 195,
    "agency": "Street Brands",
    "name": "Dennis Schrupp",
    "email": "dennis@thestreetbrands.com",
    "phone": "612.802.9892",
    "city": "",
    "state": "",
    "zip": "",
    "territory": "Branches only",
    "samples": "Cat"
  },
  {
    "agencyCode": 200,
    "agency": "Seward Associates",
    "name": "Carol Seward Paltsios",
    "address": "19 Shipley Circle",
    "email": "carolseward@sewardassoc.com",
    "phone": "978-670-9870",
    "city": "Westford",
    "state": "MA",
    "zip": "01886",
    "territory": "Principal",
    "samples": "A"
  },
  {
    "agencyCode": 200,
    "agency": "Seward Associates",
    "name": "Craig Seward",
    "address": "8 Old Farm Way",
    "email": "craigseward@sewardassoc.com",
    "phone": "978-764-2264",
    "city": "Newbury",
    "state": "MA",
    "zip": "01951",
    "territory": "Principal",
    "samples": "B"
  },
  {
    "agencyCode": 200,
    "agency": "Seward Associates",
    "name": "Christine Kurmaskie",
    "address": "463 East Center Street",
    "email": "christinekurmaskie@sewardassoc.com",
    "phone": "860-539-7487",
    "city": "Manchester",
    "state": "CT",
    "zip": "06040",
    "territory": "Connecticut",
    "samples": "B"
  },
  {
    "agencyCode": 200,
    "agency": "Seward Associates",
    "name": "Dawn Kirlin",
    "address": "651 Dennison Pond Road",
    "email": "dawnkirlin@sewardassoc.com",
    "phone": "540-272-1508",
    "city": "Francestown",
    "state": "NH",
    "zip": "03043",
    "territory": "Maine",
    "samples": "A"
  },
  {
    "agencyCode": 200,
    "agency": "Seward Associates",
    "name": "Caitlyn Paltsios",
    "address": "19 Shipley Circle",
    "email": "caitlynpaltsios@sewardassoc.com",
    "phone": "",
    "city": "Westford",
    "state": "MA",
    "zip": "01886",
    "territory": "",
    "samples": "A"
  },
  {
    "agencyCode": 200,
    "agency": "Seward Associates",
    "name": "Mariann Miceli",
    "address": "56 Phillips Street",
    "email": "mariannmiceli@sewardassoc.com",
    "phone": "401-952-4615",
    "city": "North Kingstown",
    "state": "RI",
    "zip": "02852",
    "territory": "Rhode Island",
    "samples": "A"
  },
  {
    "agencyCode": 200,
    "agency": "Seward Associates",
    "name": "Shirley J. Gratkowski",
    "address": "6 Winterberry Lane",
    "email": "shirleygratkowski@sewardassoc.com",
    "phone": "508-561-6790",
    "city": "Wareham",
    "state": "MA",
    "zip": "02571",
    "territory": "Massachussets",
    "samples": "A"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Paula Anderson",
    "address": "7973 E. Snakeroot Drive",
    "email": "paulad@salesproducertsinc.com",
    "phone": "520-603-4551",
    "city": "Tucson",
    "state": "AZ",
    "zip": "85710",
    "territory": "Southern Arizona - Tucson",
    "samples": "B"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Annie Ledford",
    "address": "48431 Indian Trails Road",
    "email": "anniel@salesproducersinc.com",
    "phone": "951-326-0616",
    "city": "Aguanga",
    "state": "CA",
    "zip": "92536",
    "territory": "Riverside/San Bernardino",
    "samples": "B"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "April Dohm",
    "address": "4516 8th Avenue",
    "email": "aprild@salesproducertsinc.com",
    "phone": "213-747-8133 ext. 117",
    "city": "Los Angeles",
    "state": "CA",
    "zip": "90043",
    "territory": "LA and Showroom MGR",
    "samples": "B"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Diane Jose",
    "address": "1549 Rosemere Court",
    "email": "dianed@salesproducertsinc.com",
    "phone": "510-499-4928",
    "city": "Fremont",
    "state": "CA",
    "zip": "94539",
    "territory": "Northern CA",
    "samples": "B"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Gigi Grande",
    "address": "4726 Nomad Drive",
    "email": "gigid@salesproducertsinc.com",
    "phone": "818-399-8919",
    "city": "Woodland Hills",
    "state": "CA",
    "zip": "91364",
    "territory": "San Fernando/San Gabriel Valley",
    "samples": "A"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Judy Chesley",
    "address": "3712 Hackett Ave",
    "email": "judyd@salesproducertsinc.com",
    "phone": "562-810-6054",
    "city": "Long Beach",
    "state": "CA",
    "zip": "90808",
    "territory": "LA -South Bay",
    "samples": "B"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Karen Hogenauer",
    "address": "1007 Oro Street",
    "email": "karend@salesproducertsinc.com",
    "phone": "949-244-0550",
    "city": "Laguna Beach",
    "state": "CA",
    "zip": "92651",
    "territory": "Orange County",
    "samples": "B"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Laura Solano",
    "address": "14065 Glenn Pines Road",
    "email": "laurad@salesproducertsinc.com",
    "phone": "530-913-6854",
    "city": "Grass Valley",
    "state": "CA",
    "zip": "95945",
    "territory": "Sacramento/Lake Tahoe/Reno",
    "samples": "B"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Patrick Council",
    "address": "14404 Glorietta Drive",
    "email": "",
    "phone": "",
    "city": "Sherman Oaks",
    "state": "CA",
    "zip": "91423",
    "territory": "Key Accounts",
    "samples": "Cat+"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Karen Hughes",
    "address": "3727 N. Mill Ridge Ave",
    "email": "",
    "phone": "",
    "city": "Springfield",
    "state": "MO",
    "zip": "65803",
    "territory": "Inside Sales/Open Territories",
    "samples": "Cat+"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Marianne Welch",
    "address": "18 Granada Place",
    "email": "marianned@salesproducertsinc.com",
    "phone": "208-670-1814",
    "city": "Burley",
    "state": "ID",
    "zip": "83318",
    "territory": "S Idaho/Utah/Wyoming",
    "samples": "A"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Kelly Oaks",
    "address": "1394 Graham Farm Circle",
    "email": "kellyd@salesproducertsinc.com",
    "phone": "505-818-0380",
    "city": "Severn",
    "state": "MD",
    "zip": "21144",
    "territory": "Key Accounts, Fresno, Hawaii 1 catalog only",
    "samples": "Cat+"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Clark Gulliford",
    "address": "10308 George Hart Ct",
    "email": "clarkd@salesproducertsinc.com",
    "phone": "405-388-9530",
    "city": "Las Vegas",
    "state": "NV",
    "zip": "89129",
    "territory": "LV, NM, N. Arizona",
    "samples": "A"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Michelle Cox",
    "address": "3244 E. Burnshide Street",
    "email": "michelled@salesproducertsinc.com",
    "phone": "503-995-9002",
    "city": "Portland",
    "state": "OR",
    "zip": "97214",
    "territory": "Oregon/SW Washington",
    "samples": "A"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Sally McGee",
    "address": "515 Coronado Street",
    "email": "sallym@salesproducersin.com",
    "phone": "",
    "city": "El Granada",
    "state": "CA",
    "zip": "94018",
    "territory": "San Francisco/North Bay",
    "samples": "B"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Stella Lynch",
    "address": "107 Via Del Cerrito",
    "email": "stellalynchservice@gmail.com",
    "phone": "",
    "city": "Encinitas",
    "state": "CA",
    "zip": "92024",
    "territory": "San Diego Trading",
    "samples": "Cat+"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Jamee Brandt",
    "address": "24265 La Montura Drive",
    "email": "jameeb@salesproducersinc.com",
    "phone": "",
    "city": "Valencia",
    "state": "CA",
    "zip": "91354",
    "territory": "Santa Barbara/San Luis Obispo",
    "samples": "B"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Mady Bradley",
    "address": "2915 South Southwind Drive",
    "email": "madyb@salesproducersinc.com",
    "phone": "",
    "city": "Gilbert",
    "state": "AZ",
    "zip": "85295",
    "territory": "Arizona",
    "samples": "A"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Lindsay De Oliverira",
    "address": "133 Spring Forest Drive",
    "email": "lindsayd@salesproducersinc.com",
    "phone": "",
    "city": "Shelby",
    "state": "",
    "zip": "28152",
    "territory": "Inside Sales/Open Territories",
    "samples": "Cat+"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Marissa Chapman Kopke",
    "email": "marissak@salesproducersinc.com",
    "phone": "303-960-6901",
    "city": "",
    "state": "",
    "zip": "",
    "territory": "",
    "samples": "A"
  },
  {
    "agencyCode": 210,
    "agency": "Sales Producers",
    "name": "Christy Suhler",
    "address": "636 Margarita Dr",
    "email": "christys@salesproducersinc.com",
    "phone": "970-481-9178",
    "city": "Grand Junction",
    "state": "CO",
    "zip": "85107",
    "territory": "Northern CO/WY",
    "samples": "A"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Abby Bell",
    "address": "1 Summer Breeze Drive",
    "email": "abby@justgot2haveit.com",
    "phone": "828-231-7471",
    "city": "Fletcher",
    "state": "NC",
    "zip": "28732",
    "territory": "West NC, North SC, East TN",
    "samples": "A"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Jan Barrick",
    "address": "3625 Scotts Mill Run",
    "email": "jan@justgot2haveit.com",
    "phone": "615-397-8110",
    "city": "Peachtree Corners",
    "state": "GA",
    "zip": "30096",
    "territory": "East TN, North AL, KY",
    "samples": "A"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Joy Daughtry",
    "address": "905 East Moran Road",
    "email": "joy@justgot2haveit.com",
    "phone": "919-619-1344",
    "city": "Brentwood",
    "state": "TN",
    "zip": "37027",
    "territory": "East NC",
    "samples": "A"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Julie Ann Maszy",
    "address": "12450 Pine Needle Lane",
    "email": "julieann@justgot2haveit.com",
    "phone": "904-728-7620",
    "city": "Miami",
    "state": "FL",
    "zip": "33156",
    "territory": "South GA, North FL",
    "samples": "A"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Irina Burns",
    "address": "2716 Ferrand Drive",
    "email": "irina@justgot2haveit.com",
    "phone": "404-285-2576",
    "city": "Durham",
    "state": "NC",
    "zip": "27705",
    "territory": "North GA",
    "samples": "A"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Jocelyn MacNair",
    "address": "400 East Bay Street, #307",
    "email": "jocelyn@justgot2haveit.com",
    "phone": "305-984-5857",
    "city": "Jacksonville",
    "state": "FL",
    "zip": "32202",
    "territory": "South FL",
    "samples": "A"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Rebecca Zamora",
    "address": "400 N. Main Street",
    "email": "rebecca@justgot2haveit.com",
    "phone": "626-353-9081",
    "city": "Winter Garden",
    "state": "FL",
    "zip": "34787",
    "territory": "Central and SW FL",
    "samples": "A"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Kim Shikle",
    "address": "16233 Tigris Road",
    "email": "kshikle@justgot2haveit.com",
    "phone": "901-647-5220",
    "city": "Fairhope",
    "state": "AL",
    "zip": "36532",
    "territory": "MS. West TN",
    "samples": "A"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Tim Gross",
    "address": "4718 Lang Ridge Drive",
    "email": "tim@justgot2haveit.com",
    "phone": "843-276-2971",
    "city": "Charleston",
    "state": "SC",
    "zip": "29405",
    "territory": "South SC, SE GA",
    "samples": "A"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Trish Ahrendt",
    "address": "685 Myrick Road",
    "email": "trish@justgot2haveit.com",
    "phone": "334-462-4780",
    "city": "Deatsville",
    "state": "AL",
    "zip": "36022",
    "territory": "Central AL, Panhandle FL",
    "samples": "A"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Katie Gale",
    "address": "27514 Park Drive",
    "email": "katie@justgot2haveit.com",
    "phone": "205-504-6826 (p)",
    "city": "Orange Beach",
    "state": "AL",
    "zip": "36561",
    "territory": "GIFT SALES MANAGER",
    "samples": "Cat+"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Michael Claussen",
    "address": "2239 Dierks Lane",
    "email": "mclaussen@justgot2haveit.com",
    "phone": "314-459-2659",
    "city": "Barnhart",
    "state": "MO",
    "zip": "63012",
    "territory": "Missouri",
    "samples": "Cat"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Jackie Miller",
    "address": "5757 Windsor Circle",
    "email": "jackie@justgot2haveit.com",
    "phone": "816-550-6652 (c)",
    "city": "Fairway",
    "state": "KS",
    "zip": "66205",
    "territory": "Nebraska Western Iowa",
    "samples": "A"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Jan Sage",
    "address": "3515 Evergreen Ave",
    "email": "jsage@justgot2haveit.com",
    "phone": "515-238-4092 (c)",
    "city": "Des Moines",
    "state": "IA",
    "zip": "50320",
    "territory": "Iowa",
    "samples": "A"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Mark Coulter",
    "address": "2239 Dierks Lane",
    "email": "mcoulter@justgot2haveit.com",
    "phone": "314-368-2398",
    "city": "Barnhart",
    "state": "MO",
    "zip": "63012",
    "territory": "Kansas",
    "samples": "A"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Tim Boyd",
    "address": "631 Myrtle Street NE #7",
    "email": "timboyd@justgot2haveit.com",
    "phone": "404-493-3195 (p)",
    "city": "Atlanta",
    "state": "GA",
    "zip": "30308",
    "territory": "KEY ACCOUNT",
    "samples": "2 catalogs"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Carla Frost",
    "address": "2387 Monterey Drive",
    "email": "carla@justgot2haveit.com",
    "phone": "404-291-8370 (p)",
    "city": "Marietta",
    "state": "GA",
    "zip": "30068",
    "territory": "KEY ACCOUNT",
    "samples": "2 catalogs"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Roger Bunn",
    "address": "100 Remsen Street 6-G",
    "email": "rogerwbunn@gmail.com",
    "phone": "718-564-4653 (p)",
    "city": "Brooklyn",
    "state": "NY",
    "zip": "11201",
    "territory": "KEY ACCOUNT",
    "samples": "2catalogs"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Lysa Buckner",
    "address": "8309 Mourning Dove Rd.",
    "email": "lysa@justgot2haveit.com",
    "phone": "754-234-4748 (p)",
    "city": "Raleigh",
    "state": "NC",
    "zip": "27615",
    "territory": "International",
    "samples": "2 catalogs"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Al Hattendorf",
    "address": "3240 Carr Drive",
    "email": "al@justgot2haveit.com",
    "phone": "703-599-7549 (P)",
    "city": "Oceanside",
    "state": "CA",
    "zip": "92056",
    "territory": "KEY ACCOUNT",
    "samples": "2 catalogs"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Michelle Morgan",
    "address": "16306 N Shore Dr",
    "email": "michelle@justgot2haveit.com",
    "phone": "678-522-4968 (p)",
    "city": "Pensacola",
    "state": "FL",
    "zip": "32507",
    "territory": "Principal",
    "samples": "2 catalogs"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Alison Blackmore",
    "address": "8 Churchill Place",
    "email": "alison@justgot2haveit.com",
    "phone": "281-684-1771 (p)",
    "city": "Avon",
    "state": "CT",
    "zip": "06001",
    "territory": "VP Sales Operations",
    "samples": "2 catalogs"
  },
  {
    "agencyCode": 215,
    "agency": "Just Got 2 Have It",
    "name": "Marla Boyd",
    "address": "12885 Dunes Lakes Terrace",
    "email": "maria@justgot2haveit.com",
    "phone": "904-874-5819 (p)",
    "city": "Jacksonville",
    "state": "FL",
    "zip": "32225",
    "territory": "SE/MINK Sales Manager",
    "samples": "catalog"
  }
];

/** Distinct agencies, in roster order. */
export const REP_AGENCIES: string[] = Array.from(new Set(SALES_REPS.map((r) => r.agency)));
